**1. Explore following functions.**

a. np.all()

b. np.any()

c. np.greater()

d. np.greater_equal()

e. np.less()

f. np.less_equal()

g. np.allclose()

h. np.identity()

i. np.nditer()

j. np.linspace()

k. np.isnan()


In [ ]:
# any()  all()
# np.all is Logical And (XAND)
# np.any is Logical OR (XOR)
import numpy as np
arr = [[True,False,False],[False,False,False]]
arr2 = [[True],[False]]
all = np.all(arr)
any = np.any(arr2)
print("all() = ",all)
print("any() = ",any)

all() =  False
any() =  True


In [ ]:
#greater and greater_equal
arr = [8,2,3,4 ]
arr2 = [8,6,7,8]
print(np.greater(arr,arr2)) 
print(np.greater_equal(arr,arr2))

[False False False False]
[ True False False False]


In [ ]:
#less and less_equal
arr = [8,2,3,4 ]
arr2 = [8,6,7,8]
print(np.less(arr,arr2)) 
print(np.less_equal(arr,arr2))

[False  True  True  True]
[ True  True  True  True]


In [ ]:
# identity()
a = np.identity(4,dtype=int)
print(a)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
arr7 = [[8,2,3,4],[10,13,14,9],[5,6,7,1]]
print(arr7)
for i  in np.nditer(arr7, order = 'F'): 
    print(i)

[[8, 2, 3, 4], [10, 13, 14, 9], [5, 6, 7, 1]]
(array(8), array(10), array(5))
(array(2), array(13), array(6))
(array(3), array(14), array(7))
(array(4), array(9), array(1))


In [ ]:
np.linspace(10,20,5)
aa = [1,2,3,np.nan]
a=np.array(aa)
print(aa)
print(np.isnan(a))

[1, 2, 3, nan]
[False False False  True]


### **2. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays**

In [ ]:
arr = np.array([10,20,30,40,50,60,70])
arr2 = np.array([70,60,50,40,30,20,10])
print(np.greater(arr,arr2))
print(np.greater_equal(arr,arr2))
print(np.less(arr,arr2))
print(np.less_equal(arr,arr2))

[False False False False  True  True  True]
[False False False  True  True  True  True]
[ True  True  True False False False False]
[ True  True  True  True False False False]


### **3. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.**

In [ ]:
arr = np.array([1,7,13,105])
print(arr.nbytes)

32


### **4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives**

In [ ]:
arr = np.zeros(10)
print(arr)
arr = np.ones(10)
print(arr)
arr = np.ones(10)*5
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


### **5. Write a NumPy program to create an array of the integers from 40 to 60**

In [ ]:
arr= np.arange(40,60)
print(arr)

[40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]


### **6. Write a NumPy program to create an array of all the even integers from 30 to 70**

In [ ]:
arr= np.arange(30,70,2)
print(arr)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


### **7. Write a NumPy program to create a 3X4 array and iterate over it.**

In [ ]:
a = np.arange(10,22).reshape((3, 4))
print("Original array:")
print(a)
print("Each element of the array is:")
for x in np.nditer(a):
  print(x,end=" ")

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

### **8. Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.**

In [ ]:
arr = np.arange(0,9).reshape(3,3)
print("array 1 :")
print(arr)
print("Sum of rows :",np.sum(arr,axis=1))
print("Sum of column :",np.sum(arr,axis=0))

array 1 :
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Sum of rows : [ 3 12 21]
Sum of column : [ 9 12 15]


### **9.Write a NumPy program to convert a given list into an array, then again convert it into a list. Check initial list and final list are equal or not.**

In [ ]:
lst=[1,2,3,4,5,6,7,8]
arr=np.array(lst)
print("Original list : ",lst)
ls=list(arr)
print("Into array : ",arr)
print("Again in  list : ",ls)
if(lst==ls):
  print("Both list are equal")

Original list :  [1, 2, 3, 4, 5, 6, 7, 8]
Into array :  [1 2 3 4 5 6 7 8]
Again in  list :  [1, 2, 3, 4, 5, 6, 7, 8]
Both list are equal


### **10.Write a NumPy program to sort a given array by row and column in ascending order.**

In [ ]:
arr=np.array([3,5,1,5,2,8,6,4]).reshape(2,4)
print("Sort by column : ")
print(np.sort(arr,axis=0))
print("Sort by rows : ")
print(np.sort(arr,axis=1))

Sort by column : 
[[2 5 1 4]
 [3 8 6 5]]
Sort by rows : 
[[1 3 5 5]
 [2 4 6 8]]


### **11.Write a NumPy program to swap rows and columns of a given array in reverse order**

In [ ]:
ar1 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print("Original arr : \n",ar1)
ar1 = ar1[::-1]
print("In reverce order  : \n",ar1)

Original arr : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
In reverce order  : 
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
